config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#homepage'
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]
  resources :posts do
    resources :comment_posts
  end

  #user login & logout
  get 'signin', to: 'sessions#new' 
  post 'signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
end

app/models/comment_post.rb
class CommentPost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comment_posts_controller.rb
class CommentPostsController < ApplicationController
  before_action :set_post
  before_action :set_comment_post, only: [:show]

  # GET /posts/:post_id/comment_posts/1
  def show
  end

  # GET /posts/:post_id/comment_posts/new
  def new
    @comment_post = @post.comment_posts.build
  end

  # POST /posts/:post_id/comment_posts
  def create
    @comment_post = @post.comment_posts.build(comment_post_params)
    @comment_post.user = current_user
  
    if @comment_post.save
      redirect_to @post, notice: 'Comment post was successfully created.'
    else
      redirect_to @post
    end
  end

  # GET /posts/:post_id/comments
  def index
    @comments = @post.comment_posts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment_post
      @comment_post = @post.comment_posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_post_params
      params.require(:comment_post).permit(:content)
    end
end

app/views/comment_posts/index.html.erb
<h1>Comments for Post: <%= @post.title %></h1>

<% @comments.each do |comment| %>
  <div>
    <p><%= comment.content %></p>
  </div>
<% end %>

app/views/comment_posts/new.html.erb
<h1>New Comment Post</h1>

<%= render 'form', comment_post: @comment_post %>

<%= link_to 'Back', post_comment_posts_path(@post) %>

app/views/comment_posts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @comment_post.content %>
</p>

<%= link_to 'Edit', edit_post_comment_post_path(@post, @comment_post) %> |
<%= link_to 'Back', post_comment_posts_path(@post) %>