config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#homepage'
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]
  resources :posts do
    resources :comment_posts
  end

  #user login & logout
  get 'signin', to: 'sessions#new' 
  post 'signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save :add_https_to_links

  has_many :posts, dependent: :destroy
  has_many :user_skills
  has_many :skills, through: :user_skills

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  def instagram_link?
    instagram_link.present?
  end

  def facebook_link?
    facebook_link.present?
  end

  def github_link?
    github_link.present?
  end

  def twitter_link?
    twitter_link.present?
  end

  private

  def add_https_to_links
    link_attributes = [:instagram_link, :linkedin_link, :facebook_link, :github_link, :twitter_link]

    link_attributes.each do |attribute|
      if self[attribute].present? && !self[attribute].start_with?('http://', 'https://')
        self[attribute] = "https://#{self[attribute]}"
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update]

  # Users lists
  def index
    @users = User.where.not(id: current_user.id)
    @current_user_index = params[:user_index].to_i || 0
    @user = @users[@current_user_index]
  end

  # Each user show route
  def show
  end

  # Signup route or new user route
  def new
    @user = User.new
  end

  # New user action
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User created successfully"
      redirect_to users_path(@user)
    else
      render 'new'
    end
  end

  # Edit user route
  def edit
    @all_skills = Skill.all
  end

  # Edit user action
  def update
    if @user.update(user_params)
      flash[:notice] = "User updated successfully"
      redirect_to users_path(@user)
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :program_name, :department, :instagram_link, :linkedin_link, :facebook_link, :github_link, :twitter_link, skill_ids: [])
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_profile_card.html.erb
<%= stylesheet_link_tag 'user_profile_card.css' %>

<div class="wrapper">
  <div class="name"><%= user.name %></div>
  <div class="about"><%= user.program_name %>, <%= user.department %></div>
 
  <div class="form_box">
    <h6 class="test-center mt-3 mb-3">Skills: </h5>
    <div class="row">
      <% user.skills.each do |skill| %>
        <div class="col-6 col-md-4 col-lg-3 mb-1">
          <span class="badge bg-primary">
            <%= skill.name %>
          </span>
        </div>
      <% end %>
    </div>
  </div>

    <div class="social-icons">
    <% if user.facebook_link? %>
      <%= link_to user.facebook_link, target: "_blank", class: "fb" do %>
        <i class="fab fa-facebook-f"></i>
      <% end %>
    <% end %>

    <% if user.twitter_link? %>
      <%= link_to user.twitter_link, target: "_blank", class: "twitter" do %>
        <i class="fab fa-twitter"></i>
      <% end %>
    <% end %>

    <% if user.instagram_link? %>
      <%= link_to user.instagram_link, target: "_blank", class: "insta" do %>
        <i class="fab fa-instagram"></i> 
      <% end %>
    <% end %>

    <% if user.github_link? %>
      <%= link_to user.github_link, target: "_blank", class: "github" do %>
        <i class="fab fa-github"></i>
      <% end %>
    <% end %>
  </div>

  <div class="links-div">
    <% if user.linkedin_link? %>
      <%= link_to user.linkedin_link, target: "_blank", class: "links", id:"linkedin" do %>
        <i class="fab fa-linkedin-in"> </i> LinkedIn
      <% end %>
    <% end %>
    <%= link_to "mailto:#{user.email}", class: "links", id:"email" do %>
      <i class="far fa-envelope"></i> Email
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'editprofile.css' %>

<div class="user-form">
  <h2 class="text-center mt-2">Edit Profile</h2>
  <section class="user-edit-form">
    <%= render '/global/errors', obj: @user %>
    <%= form_with(model: @user, data: { turbo: false }, local: true, class: "form_con") do |f| %>
      <div class="form_box">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Enter your full name", class: "form-control" %>
      </div>

      <div class="form_box email_box">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "Enter your Email", class: "form-control" %>
      </div>

      <div class="form_box">
        <%= f.label :program_name %>
        <%= f.text_field :program_name, placeholder: "Enter your program", class: "form-control" %>
      </div>

      <div class="form_box">
        <%= f.label :department %>
        <%= f.text_field :department, placeholder: "Enter your department", class: "form-control" %>
      </div>

      <div class="form_box">
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "Enter Password", class: "form-control" %>
      </div>



      <div class="skill-div">
        <h3 class="text-center mt-3 mb-3">Select Skills</h3>
          <div class="form_box">
            <div class="row">
              <% @all_skills.in_groups_of(4, false).each do |skills_group| %>
                <div class="col-lg-3 col-md-6">
                  <% skills_group.each do |skill| %>
                    <div>
                      <%= check_box_tag "user[skill_ids][]", skill.id, @user.skills.include?(skill) %>
                      <%= label_tag "user_skill_ids_#{skill.id}", skill.name %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
      </div>

      <div class="social-media-links">
        <h3 class="text-center mt-3 mb-3">Social Media Links</h3>
          <div class="form_box">
            <div class="input-group">
              <span class="input-group-text"><i class="fab fa-instagram"></i></span>
              <%= f.text_field :instagram_link, placeholder: "Enter your Instagram link", class: "form-control" %>
            </div>
          </div>
      
          <div class="form_box">
            <div class="input-group">
              <span class="input-group-text"><i class="fab fa-linkedin"></i></span>
              <%= f.text_field :linkedin_link, placeholder: "Enter your LinkedIn link", class: "form-control" %>
            </div>
          </div>
          <div class="form_box">
            <div class="input-group">
              <span class="input-group-text"><i class="fab fa-facebook"></i></span>
              <%= f.text_field :facebook_link, placeholder: "Enter your Facebook link", class: "form-control" %>
            </div>
          </div>
          
          <div class="form_box">
            <div class="input-group">
              <span class="input-group-text"><i class="fab fa-github"></i></span>
              <%= f.text_field :github_link, placeholder: "Enter your GitHub link", class: "form-control" %>
            </div>
          </div>

          <div class="form_box">
            <div class="input-group">
              <span class="input-group-text"><i class="fab fa-twitter"></i></span>
              <%= f.text_field :twitter_link, placeholder: "Enter your Twitter link", class: "form-control" %>
            </div>
          </div>
      </div>



      <div class="text-center mt-2">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary sign_btn") %>
      </div>
    <% end %>
  </section>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user_profile_card.css' %>
<div class="all-users">
  <div class="user-profile-card">
    <% if @user %>
      <%= render 'user_profile_card', user: @user %>
      <div class="navigation-buttons">
        <%= link_to "Previous", users_path(user_index: @current_user_index - 1), class: "btn btn-primary mr-2" if @current_user_index > 0 %>
        <%= link_to "Next", users_path(user_index: @current_user_index + 1), class: "btn btn-primary" if @current_user_index < @users.length - 1 %>
      </div>
    <% else %>
      <p>No more user profiles to display.</p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'login.css' %>

<div class="main-login-div">
  <div class="user-form container">
    <%= render '/global/errors', obj: @user %>
    
    <%= form_with(model: @user, data: { turbo: false }, local: true, class: "form_con") do |f| %>
      
      <div class="form-group username_box">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, placeholder: "Enter your full name", class: "form-control" %>
      </div>
    
      <div class="form-group email_box">
        <%= f.label :email, class: "form-label" %>
        <%= f.email_field :email, placeholder: "Enter your Email", class: "form-control" %>
      </div>

      <div class="form-group password_box">
        <%= f.label :password, class: "form-label" %>
        <%= f.password_field :password, placeholder: "Enter Password", class: "form-control" %>
      </div>
      
      <div class="text-center">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn sign_btn mt-4") %>
      </div>
    
    <% end %>
    <hr>
      
    <div class="alter-div text-center">
      <p>Already have an account?</p>
      <%= link_to "Log In", signin_path, class: "btn sign_btn signup_btn mt-4" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
    <h3>Name: <%= @user.name %></h3>
    <p>Email :<%= @user.email %></p>
    <p>Program :<%= @user.program_name %></p>
    <p>department : <%= @user.department %></p>

    <div class="user_links">
      <% if @user.instagram_link? %>
        <%= link_to @user.instagram_link ,target: "_blank" do%>
          <span>My instagram</span>
        <% end %>
    <% end %>
    <% if @user.linkedin_link? %>
      <%= link_to @user.linkedin_link, target: "_blank" do%>
        <span>My linkedIn</span>
      <% end %>
    <% end %> 
                                                            
    </div>


     <% if logged_in? && @user == current_user %>
     <%= link_to "Edit profile", edit_user_path(@user) %>
     <%= link_to "Delete profile", user_path(@user), 
     data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>

</div>