config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#homepage'
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]
  resources :posts do
    resources :comment_posts
  end

  #user login & logout
  get 'signin', to: 'sessions#new' 
  post 'signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment_posts, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
  
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "mt-5") do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
  <%= form.label :Title, class: "form-label", style: "font-weight: bold;" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
  <%= form.label :Content, class: "form-label", style: "font-weight: bold;" %>
  <%= form.cktext_area :content, class: "form-control" %>
</div>

  <div class="mb-3">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back to posts", posts_path, class: "btn btn-secondary mb-5" %>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag 'post.css' %>

<div id="<%= dom_id post %>" class="post mt-3">
  <h1 class="title"><%= post.title %></h1>
  <div class="content">
    <%= sanitize post.content.html_safe %>
  </div>
  <div class="author-div">
    <p class="author-name"><strong>Authored By:</strong> <%= post.user.name %></p>
    <p class="date"><strong>Posted Date:</strong> <%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing post</h1>
  <%= render "form", post: @post %>
  <div class="text-end">
    <%= link_to "Show this post", @post, class: "btn btn-danger" %>
  </div>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts.css' %>
<div class="container">
  <div class="text-end mb-4">
    <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
  </div>

  <div id="posts">
    <% @posts.each do |post| %>
      <div class="posts-card mb-3">
          <h3 class="posts-card-title"><%= post.title %></h3>
          <p class="posts-card-text"><%= truncate(strip_tags(post.content), length: 200, separator: ' ') %>
          </p>
          <%= link_to "Read more", post, class: "posts-card-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">New post</h1>

<div class="container">
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'post.css' %>

<div class="container">
  <% if current_user == @post.user %>
    <div class="d-flex justify-content-around mt-3">
      <%= link_to "Edit Post", edit_post_path(@post), class: "action-btn" %>
      <%= button_to "Delete Post", @post, method: :delete, data: { confirm: "Are you sure?" }, class: "action-btn" %>
    </div>
  <% end %>

  <%= render @post %>
  <div class="mt-3">
    <%= link_to "Back to posts", posts_path, class: "btn btn-secondary mb-5" %>
  </div>

  <h2>Comments</h2>
  <%= form_with(model: [ @post, CommentPost.new ], url: post_comment_posts_path(@post), method: :post, local: true) do |form| %>
    <div class="d-flex justify-content-around mb-5">
      <div class="form-group col-lg-10">
      <%= form.text_field :content, class: "form-control" %>
      </div>
      <%= form.submit "Add Comment", class: "btn btn-primary ml-2" %>
    </div>
  <% end %>

  <% @post.comment_posts.each do |comment| %>
    <div class="card mb-3 mt-3">
      <div class="card-body d-flex justify-content-between align-items-center">
        <p class="card-text m-0"><%= comment.content %></p>
        <div class="text-muted m-0">By: <%= comment.user.name %></div>
      </div>
    </div> 
  <% end %>
</div>