config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#homepage'
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]
  resources :posts do
    resources :comment_posts
  end

  #user login & logout
  get 'signin', to: 'sessions#new' 
  post 'signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<%= stylesheet_link_tag 'footer.css' %>
<footer class="footer">
  <div class="container">
    <p class="mb-0">Created by <%= link_to 'Jainish Patel', "https://www.linkedin.com/in/jainish31/", target: '_blank' %> as part of the Prototyping Web and Mobile Applications Course Project</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'navbar.css' %>
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <%= link_to image_tag("logo.png", alt: "Your Logo", class: "navbar-brand", style: "width: 300px; height: 100px;"), root_path %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <% if logged_in? %>
                    <div class="user-name-div">
                        <li class="nav-item">
                            <%= link_to posts_path, class: "user-links" do %>
                                <i class="fas fa-newspaper"> </i> Posts
                            <% end %>
                        </li>
                        <li class="nav-item">
                            <%= link_to edit_user_path(current_user), class: "user-links" do %>
                                <i class="fas fa-user"> </i> Profile
                            <% end %>
                        </li>
                        <li class="nav-item">
                             <%= link_to "Sign Out", signout_path, class: "nav-link", data: { turbo_method: :delete, turbo_confirm: "Sign out of Sharp" } %>
                        </li>
                    </div>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to "LogIn", signin_path, class: "nav-link" %>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>McConnect</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <script src="https://kit.fontawesome.com/2f19c80d2d.js" data-mutate-approach="sync"></script>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag '//cdn.ckeditor.com/4.16.2/standard/ckeditor.js' %>
</head>

<body>
<%= render 'layouts/navbar' %>

<!-- Bootstrap Toasts -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <!-- Toast for Notice -->
  <% if notice.present? %>
    <div class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          <%= notice %>
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  <% end %>

  <!-- Toast for Alert -->
  <% if alert.present? %>
    <div class="toast align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          <%= alert %>
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
</div>

<!-- End Bootstrap Toasts -->
<%= yield %>
<%= render 'layouts/footer' %>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

<!-- Script to initialize and show/hide toasts -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var toastNotice = new bootstrap.Toast(document.querySelector('.toast.align-items-center.bg-primary'));
        var toastAlert = new bootstrap.Toast(document.querySelector('.toast.align-items-center.bg-danger'));

        if (<%= notice.present? %>) {
            toastNotice.show();
        }

        if (<%= alert.present? %>) {
            toastAlert.show();
        }
    });
</script>
</body>
</html>